import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const HERO_HEIGHT = 360;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  scroll: { paddingBottom: 130 },
  errorWrap: { flex: 1, justifyContent: 'center' },

  heroWrap: {
    height: HERO_HEIGHT,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    backgroundColor: theme.colors.surface,
  },
  heroImageWrap: { ...StyleSheet.absoluteFillObject },
  heroImage: { width: '100%', height: '100%' },
  heroScrim: { ...StyleSheet.absoluteFillObject },
  heroBody: { padding: theme.spacing.gutter, paddingBottom: theme.spacing.l },
  heroBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.s,
    marginBottom: theme.spacing.m,
  },
  heroTitle: { ...theme.typography.h1, fontSize: 28, lineHeight: 34 },
  heroMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: theme.spacing.s,
  },
  heroMetaText: {
    ...theme.typography.bodySmall,
    color: theme.colors.text,
    flex: 1,
  },

  topBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.m,
    paddingBottom: theme.spacing.s,
  },
  topBarBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  circleButton: {
    width: theme.hitTarget,
    height: theme.hitTarget,
    borderRadius: theme.borderRadius.round,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(10,10,10,0.6)',
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },

  body: {
    paddingHorizontal: theme.spacing.gutter,
    paddingTop: theme.spacing.l,
  },
  section: { marginTop: theme.spacing.xl },

  registeredCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.m,
    padding: theme.spacing.m,
    marginBottom: theme.spacing.l,
    borderRadius: theme.borderRadius.xl,
    backgroundColor: theme.colors.primaryMuted,
    borderWidth: 1,
    borderColor: theme.colors.primarySoft,
  },
  registeredIcon: {
    width: 44,
    height: 44,
    borderRadius: theme.borderRadius.m,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(69,240,106,0.14)',
  },
  registeredCopy: { flex: 1, minWidth: 0 },
  registeredTitle: { ...theme.typography.title, fontSize: 15 },
  registeredMeta: { ...theme.typography.caption, marginTop: 2 },
  registeredAction: {
    width: 44,
    height: 44,
    borderRadius: theme.borderRadius.m,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
  },

  stats: { flexDirection: 'row', gap: theme.spacing.s },
  stat: {
    flex: 1,
    minWidth: 0,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  statLabel: { ...theme.typography.label, fontSize: 11 },
  statValue: {
    ...theme.typography.title,
    fontSize: 17,
    marginTop: theme.spacing.s,
  },
  statAccent: { color: theme.colors.primary },
  statWarn: { color: theme.colors.warning },

  schedule: { paddingLeft: 4 },
  scheduleRow: { flexDirection: 'row', gap: theme.spacing.m },
  scheduleRail: { alignItems: 'center', width: 16 },
  scheduleDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 4,
    backgroundColor: theme.colors.surfaceLight,
  },
  scheduleDotActive: { backgroundColor: theme.colors.primary },
  scheduleLine: {
    flex: 1,
    width: 2,
    marginVertical: 4,
    backgroundColor: theme.colors.border,
  },
  scheduleCopy: { flex: 1, paddingBottom: theme.spacing.l },
  scheduleTime: { ...theme.typography.title, fontSize: 15 },
  scheduleLabel: { ...theme.typography.caption, marginTop: 3 },

  joined: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.m,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  joinedText: { ...theme.typography.bodySmall, flex: 1 },

  card: {
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  about: { ...theme.typography.bodyLarge, fontSize: 15 },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginVertical: theme.spacing.m,
  },
  rulesTitle: { ...theme.typography.label, marginBottom: theme.spacing.m },
  rule: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.s,
    marginBottom: theme.spacing.s,
  },
  ruleText: { ...theme.typography.bodySmall, flex: 1 },

  fixtureList: { gap: theme.spacing.s },
  fixture: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.m,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  fixtureWhen: { alignItems: 'center', minWidth: 54 },
  fixtureDay: {
    ...theme.typography.label,
    color: theme.colors.primary,
    fontSize: 11,
  },
  fixtureTime: { ...theme.typography.title, fontSize: 15, marginTop: 3 },
  fixtureTeams: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.s,
  },
  fixtureTeam: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.s,
    minWidth: 0,
  },
  fixtureMark: { width: 24, height: 24, borderRadius: 12 },
  fixtureTeamName: {
    ...theme.typography.caption,
    color: theme.colors.text,
    fontFamily: theme.font.semibold,
    flex: 1,
  },
  fixtureVs: {
    ...theme.typography.label,
    color: theme.colors.textMuted,
    fontSize: 11,
  },

  organizer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.m,
  },
  organizerCopy: { flex: 1, minWidth: 0 },
  organizerName: { ...theme.typography.title, fontSize: 15 },
  organizerMeta: { ...theme.typography.caption, marginTop: 2 },

  venueCard: {
    borderRadius: theme.borderRadius.xl,
    overflow: 'hidden',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  venueImageWrap: {
    height: 160,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    padding: theme.spacing.m,
  },
  venueImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  directions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 38,
    paddingHorizontal: theme.spacing.m,
    borderRadius: theme.borderRadius.m,
    backgroundColor: theme.colors.primary,
  },
  directionsText: {
    ...theme.typography.caption,
    color: theme.colors.onPrimary,
    fontFamily: theme.font.bold,
  },
  venueBody: { padding: theme.spacing.m },
  venueName: { ...theme.typography.title, fontSize: 16 },
  venueAddress: { ...theme.typography.bodySmall, marginTop: 4 },
  venueRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: theme.spacing.s,
  },
  venueRatingText: {
    ...theme.typography.caption,
    color: theme.colors.text,
    fontFamily: theme.font.bold,
  },

  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.m,
    paddingHorizontal: theme.spacing.gutter,
    paddingTop: theme.spacing.m,
    backgroundColor: theme.colors.surface,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  priceBlock: { minWidth: 74 },
  priceLabel: { ...theme.typography.label, fontSize: 11 },
  priceValue: {
    ...theme.typography.title,
    fontSize: 19,
    color: theme.colors.primary,
    marginTop: 2,
  },
  joinButton: { flex: 1 },
});
