import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const HERO_GAP = theme.spacing.m;
export const MAX_HERO = 5;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  scroll: { paddingTop: theme.spacing.s },
  carouselSeparator: { width: theme.spacing.m },

  glow: {
    position: 'absolute',
    top: -120,
    left: -60,
    right: -60,
    height: 500,
    borderRadius: 200,
    overflow: 'hidden',
  },

  header: { marginBottom: theme.spacing.m },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.gutter,
    marginBottom: theme.spacing.m,
  },
  identity: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
  },
  identityCopy: { flex: 1, marginLeft: theme.spacing.m, minWidth: 0 },
  greeting: { ...theme.typography.caption },
  name: { ...theme.typography.h3, marginTop: 2 },
  headerActions: {
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.s,
    marginLeft: theme.spacing.s,
  },
  iconButton: {
    width: theme.hitTarget,
    height: theme.hitTarget,
    borderRadius: theme.borderRadius.l,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  badgeDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
    borderWidth: 2,
    borderColor: theme.colors.surface,
  },
  badgeDotText: {
    color: theme.colors.onPrimary,
    fontFamily: theme.font.extrabold,
    fontSize: 10,
  },

  locationChip: {
    flexShrink: 1,
    minWidth: 92,
    maxWidth: 132,
    height: theme.hitTarget,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    borderRadius: theme.borderRadius.round,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  locationText: {
    ...theme.typography.caption,
    color: theme.colors.text,
    flexShrink: 1,
    minWidth: 0,
  },

  searchRow: {
    paddingHorizontal: theme.spacing.gutter,
    marginBottom: theme.spacing.l,
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.s,
    height: 52,
    paddingHorizontal: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  searchPlaceholder: { ...theme.typography.bodySmall, flex: 1 },
  searchHint: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },

  nextUp: {
    marginHorizontal: theme.spacing.gutter,
    marginBottom: theme.spacing.l,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.xl,
    overflow: 'hidden',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.primarySoft,
    ...theme.elevation.low,
  },
  nextUpTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.s,
  },
  nextUpCountdown: {
    ...theme.typography.caption,
    color: theme.colors.primary,
    fontFamily: theme.font.bold,
  },
  nextUpTitle: {
    ...theme.typography.h3,
    marginTop: theme.spacing.m,
    marginBottom: theme.spacing.s,
  },
  nextUpMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 5,
  },
  nextUpMetaText: { ...theme.typography.bodySmall, flex: 1 },
  nextUpActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.s,
    marginTop: theme.spacing.m,
  },
  nextUpPrimary: {
    flex: 1,
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: theme.borderRadius.m,
    backgroundColor: theme.colors.primary,
  },
  nextUpPrimaryText: { ...theme.typography.button, fontSize: 14 },
  nextUpSecondary: {
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: theme.spacing.m,
    borderRadius: theme.borderRadius.m,
    backgroundColor: theme.colors.surfaceLight,
  },
  nextUpSecondaryText: {
    ...theme.typography.caption,
    color: theme.colors.text,
    fontFamily: theme.font.bold,
  },

  heroBlock: { marginBottom: theme.spacing.l },
  heroList: { paddingHorizontal: theme.spacing.gutter, gap: HERO_GAP },
  hero: {
    height: 300,
    borderRadius: theme.borderRadius.xl,
    overflow: 'hidden',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.surface,
    ...theme.elevation.medium,
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  heroTopRow: {
    flexDirection: 'row',
    gap: theme.spacing.s,
    padding: theme.spacing.m,
  },
  heroBody: { padding: theme.spacing.m },
  heroSport: { ...theme.typography.label, color: theme.colors.textSecondary },
  heroTitle: { ...theme.typography.h2, marginTop: 6 },
  heroMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: theme.spacing.s,
  },
  heroMetaText: {
    ...theme.typography.bodySmall,
    color: theme.colors.text,
    flex: 1,
  },
  heroFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: theme.spacing.m,
    gap: theme.spacing.m,
  },
  heroAttending: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  heroAttendingText: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
  },
  heroCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    height: 42,
    paddingHorizontal: theme.spacing.m,
    borderRadius: theme.borderRadius.m,
    backgroundColor: theme.colors.primary,
  },
  heroCtaText: { ...theme.typography.button, fontSize: 14 },

  dots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    marginTop: theme.spacing.m,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.surfaceLight,
  },

  sportChipsScroll: { flexGrow: 0, marginBottom: theme.spacing.l },
  sportChips: { paddingHorizontal: theme.spacing.gutter, gap: theme.spacing.s },
  sportChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    minHeight: 38,
    paddingHorizontal: 14,
    borderRadius: theme.borderRadius.round,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  sportChipText: {
    ...theme.typography.caption,
    color: theme.colors.text,
    fontFamily: theme.font.semibold,
  },

  section: { marginBottom: theme.spacing.xl },
  sectionHeader: { paddingHorizontal: theme.spacing.gutter },
  friendsList: {
    paddingHorizontal: theme.spacing.gutter,
    gap: theme.spacing.s,
  },
  rail: { paddingHorizontal: theme.spacing.gutter },

  card: {
    borderRadius: theme.borderRadius.xl,
    overflow: 'hidden',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  cardImageWrap: { height: 148, backgroundColor: theme.colors.surfaceLight },
  cardImage: { width: '100%', height: '100%' },
  cardImageTop: {
    position: 'absolute',
    top: theme.spacing.s,
    left: theme.spacing.s,
    flexDirection: 'row',
    gap: 6,
  },
  cardBody: { padding: theme.spacing.m },
  cardTitle: { ...theme.typography.title, minHeight: 44 },
  cardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 7,
  },
  cardMetaText: { ...theme.typography.caption, flex: 1 },
  cardMetaAccent: {
    color: theme.colors.primary,
    fontFamily: theme.font.semibold,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: theme.spacing.m,
    paddingTop: theme.spacing.m,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  cardPrice: {
    ...theme.typography.title,
    fontSize: 17,
    color: theme.colors.primary,
  },
  cardPriceLabel: { ...theme.typography.caption, fontSize: 11, marginTop: 3 },
  cardArrow: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
  },
  cardCta: {
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: theme.spacing.m,
    borderRadius: theme.borderRadius.m,
    backgroundColor: theme.colors.primary,
  },
  cardCtaText: { ...theme.typography.button, fontSize: 14 },

  venueCard: { gap: 4 },
  venueImageWrap: {
    height: 128,
    borderRadius: theme.borderRadius.l,
    overflow: 'hidden',
    marginBottom: theme.spacing.s,
    backgroundColor: theme.colors.surfaceLight,
  },
  venueImage: { width: '100%', height: '100%' },
  rating: {
    position: 'absolute',
    top: theme.spacing.s,
    right: theme.spacing.s,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: theme.borderRadius.s,
    backgroundColor: 'rgba(10,10,10,0.78)',
  },
  ratingText: {
    color: theme.colors.text,
    fontFamily: theme.font.bold,
    fontSize: 11,
  },
  venueName: { ...theme.typography.title, fontSize: 15 },
  venueCity: { ...theme.typography.caption },
  venuePrice: {
    ...theme.typography.title,
    fontSize: 15,
    color: theme.colors.primary,
    marginTop: 4,
  },
  venuePriceUnit: {
    ...theme.typography.caption,
    color: theme.colors.textMuted,
  },

  fixture: {
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  fixtureDate: { ...theme.typography.label, color: theme.colors.textSecondary },
  fixtureTeams: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: theme.spacing.m,
  },
  fixtureTeam: { flex: 1, alignItems: 'center', gap: 8 },
  fixtureMark: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 3,
    borderColor: theme.colors.borderSoft,
  },
  fixtureTeamName: {
    ...theme.typography.caption,
    color: theme.colors.text,
    fontFamily: theme.font.bold,
    textAlign: 'center',
  },
  fixtureVs: {
    ...theme.typography.label,
    color: theme.colors.textMuted,
    paddingHorizontal: theme.spacing.s,
  },
  fixtureEvent: {
    ...theme.typography.caption,
    marginTop: theme.spacing.m,
    textAlign: 'center',
  },

  communityList: {
    paddingHorizontal: theme.spacing.gutter,
    gap: theme.spacing.s,
  },
  communityRow: {
    flexDirection: 'row',
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  communityCopy: { flex: 1, marginLeft: theme.spacing.m, minWidth: 0 },
  communityTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.s,
  },
  communityAuthor: { ...theme.typography.title, fontSize: 14, flex: 1 },
  communityTime: { ...theme.typography.caption, fontSize: 11 },
  communityText: {
    ...theme.typography.bodySmall,
    color: theme.colors.textSecondary,
    marginTop: 5,
  },
  communityStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: theme.spacing.s,
  },
  communityStat: { ...theme.typography.caption, fontSize: 11 },

  staleBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.s,
    marginHorizontal: theme.spacing.gutter,
    marginBottom: theme.spacing.m,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: theme.colors.warningMuted,
    borderWidth: 1,
    borderColor: 'rgba(251,146,60,0.24)',
  },
  staleText: {
    ...theme.typography.caption,
    color: theme.colors.warning,
    flex: 1,
  },

  skeleton: { paddingHorizontal: theme.spacing.gutter, gap: theme.spacing.l },
  skeletonActions: { flexDirection: 'row', justifyContent: 'space-between' },
  skeletonAction: { alignItems: 'center', gap: 9 },
  skeletonRail: { flexDirection: 'row', gap: theme.spacing.m },
});
